"""create farm world model core

Revision ID: 0b25e9284e03
Revises: 
Create Date: 2026-09-23 18:39:48.138434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b25e9284e03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('management_unit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_cycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('management_unit_id', sa.UUID(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('cultivar', sa.String(length=100), nullable=True),
    sa.Column('planted_on', sa.Date(), nullable=True),
    sa.Column('tree_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['management_unit_id'], ['management_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('management_unit_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('occurred_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycle.id'], ),
    sa.ForeignKeyConstraint(['management_unit_id'], ['management_unit.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_crop_cycle_id'), 'event', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_management_unit_id'), 'event', ['management_unit_id'], unique=False)
    op.create_index(op.f('ix_event_occurred_start'), 'event', ['occurred_start'], unique=False)
    op.create_index(op.f('ix_event_recorded_at'), 'event', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_recorded_at'), table_name='event')
    op.drop_index(op.f('ix_event_occurred_start'), table_name='event')
    op.drop_index(op.f('ix_event_management_unit_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_crop_cycle_id'), table_name='event')
    op.drop_table('event')
    op.drop_table('crop_cycle')
    op.drop_table('management_unit')
    op.drop_table('farm')
    # ### end Alembic commands ###
