"""add knowledge retrieval chunks

Revision ID: 16ea420c3258
Revises: 65fb51710a44
Create Date: 2026-09-24 16:05:30.762492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ea420c3258'
down_revision: Union[str, Sequence[str], None] = '65fb51710a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, coalesce(content, ''))", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'chunk_index', name='uq_knowledge_chunk_source_index')
    )
    op.create_index(op.f('ix_knowledge_chunk_crop'), 'knowledge_chunk', ['crop'], unique=False)
    op.create_index('ix_knowledge_chunk_search_vector', 'knowledge_chunk', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_knowledge_chunk_source_id'), 'knowledge_chunk', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunk_source_id'), table_name='knowledge_chunk')
    op.drop_index('ix_knowledge_chunk_search_vector', table_name='knowledge_chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_knowledge_chunk_crop'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    # ### end Alembic commands ###
