"""add evidence and agronomic assertions

Revision ID: 1978d6de5ce6
Revises: 0b25e9284e03
Create Date: 2026-09-24 12:30:55.639187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1978d6de5ce6'
down_revision: Union[str, Sequence[str], None] = '0b25e9284e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agronomic_assertion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assertion_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=False),
    sa.Column('object_text', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agronomic_assertion_assertion_type'), 'agronomic_assertion', ['assertion_type'], unique=False)
    op.create_index(op.f('ix_agronomic_assertion_crop'), 'agronomic_assertion', ['crop'], unique=False)
    op.create_table('evidence_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_source_source_type'), 'evidence_source', ['source_type'], unique=False)
    op.create_table('assertion_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assertion_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('locator', sa.String(length=500), nullable=False),
    sa.Column('support_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assertion_id'], ['agronomic_assertion.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assertion_id', 'source_id', 'locator', name='uq_assertion_evidence_locator')
    )
    op.create_index(op.f('ix_assertion_evidence_assertion_id'), 'assertion_evidence', ['assertion_id'], unique=False)
    op.create_index(op.f('ix_assertion_evidence_source_id'), 'assertion_evidence', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assertion_evidence_source_id'), table_name='assertion_evidence')
    op.drop_index(op.f('ix_assertion_evidence_assertion_id'), table_name='assertion_evidence')
    op.drop_table('assertion_evidence')
    op.drop_index(op.f('ix_evidence_source_source_type'), table_name='evidence_source')
    op.drop_table('evidence_source')
    op.drop_index(op.f('ix_agronomic_assertion_crop'), table_name='agronomic_assertion')
    op.drop_index(op.f('ix_agronomic_assertion_assertion_type'), table_name='agronomic_assertion')
    op.drop_table('agronomic_assertion')
    # ### end Alembic commands ###
