"""add decision type to decision requirements

Revision ID: 65fb51710a44
Revises: ea9e9c1ce4aa
Create Date: 2026-09-24 14:42:41.679575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fb51710a44'
down_revision: Union[str, Sequence[str], None] = 'ea9e9c1ce4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_requirement', sa.Column('decision_type', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_decision_requirement_decision_type'), 'decision_requirement', ['decision_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_requirement_decision_type'), table_name='decision_requirement')
    op.drop_column('decision_requirement', 'decision_type')
    # ### end Alembic commands ###
