"""add dense chunk embeddings

Revision ID: 680aa39700b6
Revises: 16ea420c3258
Create Date: 2026-09-24 18:05:06.974050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '680aa39700b6'
down_revision: Union[str, Sequence[str], None] = '16ea420c3258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunk', sa.Column('embedding', Vector(dim=1024), nullable=True))
    op.add_column('knowledge_chunk', sa.Column('embedding_model', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunk', 'embedding_model')
    op.drop_column('knowledge_chunk', 'embedding')
    # ### end Alembic commands ###
