"""add evidence backed decision requirements

Revision ID: ea9e9c1ce4aa
Revises: 1978d6de5ce6
Create Date: 2026-09-24 14:18:45.117976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9e9c1ce4aa'
down_revision: Union[str, Sequence[str], None] = '1978d6de5ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_requirement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assertion_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['assertion_id'], ['agronomic_assertion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assertion_id', name='uq_decision_requirement_assertion')
    )
    op.create_index(op.f('ix_decision_requirement_assertion_id'), 'decision_requirement', ['assertion_id'], unique=False)
    op.create_index(op.f('ix_decision_requirement_crop'), 'decision_requirement', ['crop'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_requirement_crop'), table_name='decision_requirement')
    op.drop_index(op.f('ix_decision_requirement_assertion_id'), table_name='decision_requirement')
    op.drop_table('decision_requirement')
    # ### end Alembic commands ###
